// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_8wZRmPOMokSN6qSTw79pQuP6c4UPhHM',
    appId: '1:1096515087253:web:f5e1c87194e65154f4e49c',
    messagingSenderId: '1096515087253',
    projectId: 'consulting-chat',
    authDomain: 'consulting-chat.firebaseapp.com',
    storageBucket: 'consulting-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtdDdlOkv7tkwgXKlLxe3zPhsJXuH408g',
    appId: '1:1096515087253:android:889e4d35f513bb92f4e49c',
    messagingSenderId: '1096515087253',
    projectId: 'consulting-chat',
    storageBucket: 'consulting-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGnJaR3qkF7sM3jzcbqQK4NAn-_HS4gpE',
    appId: '1:1096515087253:ios:091b5c03a2ebef30f4e49c',
    messagingSenderId: '1096515087253',
    projectId: 'consulting-chat',
    storageBucket: 'consulting-chat.appspot.com',
    iosClientId: '1096515087253-09biv8m178b7f6dhm7s4kamaebn9951t.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatConsulting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGnJaR3qkF7sM3jzcbqQK4NAn-_HS4gpE',
    appId: '1:1096515087253:ios:091b5c03a2ebef30f4e49c',
    messagingSenderId: '1096515087253',
    projectId: 'consulting-chat',
    storageBucket: 'consulting-chat.appspot.com',
    iosClientId: '1096515087253-09biv8m178b7f6dhm7s4kamaebn9951t.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatConsulting',
  );
}
